# Generated by Django 6.0 on 2026-03-03 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_userprofile_alter_journalentry_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="tagged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this entry was last auto-tagged by the LLM",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#6b7280", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="entries", to="journal.tag"
            ),
        ),
    ]
